### ISSUE TITLE
Mailing Fusion Stones

### ISSUE THREAD

**Issue by rolenun** [jagodragon/UltimateMailMod#1]
After mailing 30 fusion stones, an error came back with [UltimateMailMod] Automation process failed - process halted. After the error, the most mails that could be sent by automation was 2 before the error would occur. After 5 minutes, the limit was increased to 15. This may be a game feature. Upon further discussion with another guildie, he identified that sending items, such as belts, did not suffer from this restriction. The only downside is that there is no custom select all button so each belt has to be selected individually for mailing.

**Comment by jagodragon** [comment]
Closing this as it is not some thing that i can fix....
